In [98]:
#prepare data downloaded from UCL
import tensorflow as tf
import xlrd
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore") #suppress warnings
import matplotlib.pyplot as plt
from keras import Sequential
from tensorflow import lite
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam



from tensorflow.keras import models
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing


from sklearn.metrics import mean_squared_error

print("hello home!")
# add header names
headers =  ['shib',"ertefaae_sine",
        'ertefaae_kol','mohit_dar_nim_metr', 'result']
heart_df = pd.read_excel('trees.xlsx',sheet_name='Vol_Zaraieb_1', usecols=headers)

#convert input to numpy arrays
X = heart_df.drop(columns=['result'])

y_label = heart_df['result'].values.reshape(X.shape[0], 1)
#print("heart_df['result']: {}".format(heart_df['result'], '2.4f'))
#print("y_label: {}".format(y_label, '2.4f'))


#split data into train and test set
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y_label, test_size=0.01, random_state=2)
#print("ytrain: {}".format(ytrain, '2.4f'))


def MyMinMaxScaler(data):    
    for i in range(len(data[0])):
        #print(f"i is {i}")
        mymin = data[:,i].min()
        mymax = data[:,i].max()
        for j in range(len(data)):
            data[j][i] = (data[j][i] - mymin) / (mymax - mymin)
    return data


originalResults = copy.deepcopy(ytrain);
#standardize the dataset
#scX = preprocessing.MinMaxScaler()
#scX = preprocessing.StandardScaler()

#scX.fit(Xtrain)
#Xtrain = scX.transform(Xtrain)
#Xtest = scX.transform(Xtest)

#print(f"Xtrain is: {Xtrain}")
Xtrain = Xtrain.to_numpy()
Xtrain = MyMinMaxScaler(Xtrain)
ytrain = MyMinMaxScaler(ytrain)

#scY = preprocessing.MinMaxScaler()
#scY = preprocessing.StandardScaler()
#scY.fit(ytrain)

#ytrain = scY.transform(ytrain)
#ytest = scY.transform(ytest)
print(f"Shape of train set is {Xtrain.shape}")
#print(f"Shape of test set is {Xtest.shape}")
print(f"Shape of train label is {ytrain.shape}")
#print(f"Shape of test labels is {ytest.shape}")

# define the model
model = Sequential()
model.add(Dense(3, input_shape=(4,)))
model.add(Dense(1, activation='sigmoid'))

# compile the model
opt = Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='mse', metrics=['accuracy','mse'])

hist = model.fit(Xtrain, ytrain, epochs=10, verbose=0,shuffle=True, validation_split=0.1, batch_size=4)



# train_pred = model.predict(Xtrain)
# test_pred = model.predict(Xtest)
# print("Train accuracy of keras neural network: {}".format(mean_squared_error(train_pred, ytrain)))
# print("Test accuracy of keras neural network: {}".format(mean_squared_error(test_pred, ytest)))
# print("\n")
# print(heart_df.head())

# plt.scatter(test_pred, ytest)

# keras_file='cf.h5'
# models.save_model(model,keras_file)
# converter=tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
# tfmodel = converter.convert()
# open("degree.tflite","wb").write(tfmodel)
print("done!")

hello home!
Shape of train set is (197, 4)
Shape of train label is (197, 1)
done!


In [99]:
import copy
# sc = preprocessing.MinMaxScaler()
sampleInput = np.array([[45,436,15.3,252],[40,480,17.4,266],[30,504,15.8,266],[30,480,14.2,260],[45,3706,31,1696]]);
print("Sample Inputs are: {}".format(sampleInput, '2.4f1'))
#sampleInput = scX.transform(sampleInput)
sampleInput = MyMinMaxScaler(sampleInput)
#sampleInput = [Xtrain[10],Xtrain[11],Xtrain[12],Xtrain[13]];
# sc.fit(sampleInput)

print("Scaled Sample Inputs are: {}".format(sampleInput, '2.4f'))
sampleInputResult = model.predict(sampleInput)

# scRev = preprocessing.MinMaxScaler()
# scRev.fit(originalResults)

def reverseMinMaxScale(data, originalData):    
    reversedData = copy.deepcopy(data)
    mymin = originalData.min()
    mymax = originalData.max()
    index = 0;
    for item in reversedData: 
        reversedData[index] = (item * (mymax - mymin)) + mymin
        index+=1
    return reversedData;
        

print("Scaled results are: {}".format(sampleInputResult, '2.4f'))
print("Manual Reverse scaled predicted results are: {}".format(reverseMinMaxScale(sampleInputResult, originalResults), '2.4f'))
print("inverse_transform results are: {}".format(scY.inverse_transform(sampleInputResult), '2.4f'))


print("expected (original) results are: {}".format([0.090,0.103,0.114,0.087,19.391], '2.4f'))

model.summary()


Sample Inputs are: [[  45.   436.    15.3  252. ]
 [  40.   480.    17.4  266. ]
 [  30.   504.    15.8  266. ]
 [  30.   480.    14.2  260. ]
 [  45.  3706.    31.  1696. ]]
Scaled Sample Inputs are: [[1.         0.         0.06547619 0.        ]
 [0.66666667 0.01345566 0.19047619 0.00969529]
 [0.         0.02079511 0.0952381  0.00969529]
 [0.         0.01345566 0.         0.00554017]
 [1.         1.         1.         1.        ]]
Scaled results are: [[0.25293076]
 [0.27372372]
 [0.3123536 ]
 [0.31070155]
 [0.27768576]]
Manual Reverse scaled predicted results are: [[ 8.137027 ]
 [ 8.798804 ]
 [10.028278 ]
 [ 9.9756975]
 [ 8.924905 ]]
inverse_transform results are: [[ 8.137028]
 [ 8.798805]
 [10.028278]
 [ 9.975698]
 [ 8.924905]]
expected (original) results are: [0.09, 0.103, 0.114, 0.087, 19.391]
Model: "sequential_32"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_69 (Dense)             (None,

In [44]:
test_pred = model.predict(Xtest)

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(test_pred, ytest)

In [ ]:
plt.scatter(test_pred, ytest)

In [ ]:
np.max(ytrain), np.min(ytrain)

In [3]:
import matplotlib.pyplot as plt 
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [4]:
plt.figure(figsize=(15,4))
plt.plot(hist.history['mse'], c='red')
plt.plot(hist.history['val_mse'], c='blue')

NameError: name 'plt' is not defined